---
title: "Ward_DJFMP_explore"
author: "Ward, A."
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls()) #clean environment

library(here)
knitr::opts_knit$set(
  root.dir = here::here()
)

knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r packages, include=FALSE}
library(readr)
library(tidyverse)
library(readxl) 
library(dplyr)
library(janitor) 
library (stringr)
library(openxlsx)
library(stats)
library(car)
library(ggplot2)
library(ggpubr)
```

#Import Data
```{r loading in data}
#loading in data
sample_sites <- read_csv("./data/processed/sample_sites.csv")
taxonomy <- read_csv("./data/processed/taxonomy.csv")
trawl_02_25 <- read_csv("./data/processed/trawl_02_25.csv")
trawl_76_01 <- read_csv("./data/processed/trawl_76_01.csv")
```

#Data Cleaning and Tidying
```{r}
#Separate sample date into day, month year
trawl_76_01 <- trawl_76_01 %>% 
  separate(SampleDate, into = c('month', 'day', 'year'), sep = "/", remove = FALSE)

trawl_02_25 <- trawl_02_25 %>% 
  separate(SampleDate, into = c('month', 'day', 'year'), sep = "/", remove = FALSE)

trawl_76_01 <- trawl_76_01 %>%
  mutate(
    month = factor(
      month,
      levels = 1:12,
      labels = month.abb,
      ordered = TRUE
    )
  )

trawl_02_25 <- trawl_02_25 %>%
  mutate(
    month = factor(
      month,
      levels = 1:12,
      labels = month.abb,
      ordered = TRUE
    )
  )

combo_trawl <- bind_rows(trawl_76_01, trawl_02_25)
combo_trawl$year <- as.numeric(combo_trawl$year)

```

#Unique species over the years
```{r}
unique(combo_trawl$CommonName)

#Species
species_by_year <- combo_trawl %>%
  filter(!is.na(CommonName)) %>%
  group_by(year, CommonName) %>%
  summarise(count = n(), .groups = "drop") %>%
  arrange(year, desc(count))

species_by_year

ggplot(species_by_year, aes(x = year, y = count, color = CommonName)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  theme(
    legend.position = "none")


```
#salmonids over years
```{r}
salmonids_by_year <- combo_trawl %>%
  filter(!is.na(CommonName)) %>%
  filter(CommonName == "steelhead" | CommonName == "Chinook Salmon") %>% 
  group_by(year, CommonName) %>%
  summarise(count = n(), .groups = "drop") %>%
  arrange(year, desc(count))

salmonids_by_year

#Chinook by year
ggplot(salmonids_by_year %>% 
         filter(CommonName =="Chinook Salmon"), aes(x = year, y = count)) +
  geom_line() +
  geom_point() +
  theme_minimal()

#Steelhead by year
ggplot(salmonids_by_year %>% 
         filter(CommonName =="steelhead"), aes(x = year, y = count)) +
  geom_line() +
  geom_point() +
  theme_minimal()

```
#looking at avg water temp by year
```{r}
#Cal avg water etmp by year
avg_temp_by_year <- combo_trawl %>%
  group_by(year) %>%
  summarise(avg_temp = mean(WaterTemp, na.rm = TRUE),
            .groups = "drop")

#temp/ salmon plot data
temp_sal_plot_data <- left_join(salmonids_by_year, avg_temp_by_year, by = "year")

#Scale for dual axis plotting
scale_factor <- max(temp_sal_plot_data$count, na.rm = TRUE) / 
                max(temp_sal_plot_data$avg_temp, na.rm = TRUE)

temp_sal_plot_data <- temp_sal_plot_data %>%
  mutate(temp_scaled = avg_temp * scale_factor)

#Dual axis plot
ggplot(temp_sal_plot_data, aes(x = year)) +
  geom_line(aes(y = count, color = CommonName), size = 1) +
  geom_line(aes(y = temp_scaled, color = "Avg Water Temp"), 
            linetype = "dashed", size = 1) +
  scale_y_continuous(
    name = "Salmon Count",
    sec.axis = sec_axis(~ . / scale_factor,
                        name = "Average Water Temperature")
  ) +
  
  theme_minimal() 


```





#Looking at avg water temp by year and location
```{r}
avg_temp_table1 <- trawl_76_01 %>%
  group_by(year, Location) %>%
  summarise(
    avg_WaterTemp = mean(WaterTemp, na.rm = TRUE),
    .groups = "drop"
  )

avg_temp_table1


ggplot(avg_temp_table1, aes(x = as.numeric(year), y = avg_WaterTemp, color = Location)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
   geom_smooth(
      aes(group = 1),
      method = "lm",
      se = TRUE,
      color = "black",
      linewidth = 1.2,
      linetype = "dashed"
    ) +
  labs(
    title = "Average Water Temperature Over Time by Location",
    x = "Year",
    y = "Average Water Temperature"
  ) +
  theme_minimal()

avg_temp_table2 <- trawl_02_25 %>%
  group_by(year, Location) %>%
  summarise(
    avg_WaterTemp = mean(WaterTemp, na.rm = TRUE),
    .groups = "drop"
  )

avg_temp_table2

ggplot(avg_temp_table2, aes(x = as.numeric(year), y = avg_WaterTemp, color = Location)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
   geom_smooth(
      aes(group = 1),
      method = "lm",
      se = TRUE,
      color = "black",
      linewidth = 1.2,
      linetype = "dashed"
    ) +
  labs(
    title = "Average Water Temperature Over Time by Location",
    x = "Year",
    y = "Average Water Temperature"
  ) +
  theme_minimal()


```
#Looking at seasonal water temp differences
```{r}
ggplot(trawl_76_01, aes(x = month, y = WaterTemp)) +
  geom_boxplot(fill = "skyblue", alpha = 0.7) +
  labs(
    x = "Month",
    y = "Water Temperature"
  ) +
  theme_minimal()

ggplot(trawl_02_25, aes(x = month, y = WaterTemp)) +
  geom_boxplot(fill = "skyblue", alpha = 0.7) +
  labs(
    x = "Month",
    y = "Water Temperature"
  ) +
  theme_minimal()

seasonal_means <- trawl_76_01 %>%
  group_by(month) %>%
  summarise(
    avg_WaterTemp = mean(WaterTemp, na.rm = TRUE),
    .groups = "drop"
  )

ggplot(seasonal_means, aes(x = month, y = avg_WaterTemp, group = 1)) +
  geom_point(size = 3) +
  geom_line(linewidth = 1) +
  labs(
    title = "Average Seasonal Cycle of Water Temperature",
    x = "Month",
    y = "Average Water Temperature"
  ) +
  theme_minimal()


trawl_76_01 <- trawl_76_01 %>%
  mutate(
    season = case_when(
      month %in% c("Dec", "Jan", "Feb") ~ "Winter",
      month %in% c("Mar", "Apr", "May") ~ "Spring",
      month %in% c("Jun", "Jul", "Aug") ~ "Summer",
      month %in% c("Sep", "Oct", "Nov") ~ "Fall"
    )
  )

ggplot(trawl_76_01, aes(x = season, y = WaterTemp)) +
  #facet_wrap(~year) +
  geom_boxplot(fill = "tan", alpha = 0.7)

```
Ok fixed water temp seasonality 

Are seasonal water temps sig different?
```{r}
seasonal_avg_76_01 <- trawl_76_01 %>%
  group_by(year, season) %>%
  summarise(
    avg_WaterTemp = mean(WaterTemp, na.rm = TRUE),
    .groups = "drop"
  )

anova_season1 <- aov(avg_WaterTemp ~ season, data = seasonal_avg_76_01)
summary(anova_season1)
```

Basic Map of Sample Sites
```{r}
library(sf)
library(terra)
library(dplyr)
library(spData)
#install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")

library(spDataLarge)
#install.packages("tmap", repos = c("https://r-tmap.r-universe.dev","https://cloud.r-project.org"))
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(ggplot2) # tidyverse data visualization package
library(ggthemes)
library(rnaturalearth) #more base maps

library(osmdata) #waterway data
library(elevatr) #elevations
library(nhdplusTools) #NHD datasets

```

```{r}
# Bounding box coordinates (min lon, min lat, max lon, max lat)
delta_bbox <- st_bbox(c(xmin = -122.7, ymin = 37.9, xmax = -121.3, ymax = 38.8),
                      crs = st_crs(4326))

delta_bbox_sf <- st_as_sfc(delta_bbox)
```

```{r}
#waterways
water_osm <- opq(bbox = delta_bbox) %>%
  add_osm_feature(key = "waterway") %>%
  osmdata_sf()

# extract rivers, canals, etc
rivers <- water_osm$osm_lines
```

```{r}
#lakes 
lakes_osm <- opq(bbox = delta_bbox) %>%
  add_osm_feature(key = "natural", value = "water") %>%
  osmdata_sf()

water_polygons <- lakes_osm$osm_polygons
```

```{r}
ggplot() +
  geom_sf(data = st_crop(water_polygons, delta_bbox),
          fill = "lightblue", color = NA) +
  geom_sf(data = st_crop(rivers, delta_bbox),
          color = "blue", size = 0.3) +
  coord_sf(xlim = c(delta_bbox$xmin, delta_bbox$xmax),
           ylim = c(delta_bbox$ymin, delta_bbox$ymax)) +
  theme_minimal()
```


```{r}
tmap_mode("plot")  # or "view" for interactive

tm_shape(delta_bbox_sf) +
  tm_polygons(alpha = 0) +
tm_shape(water_polygons) +
  tm_fill(col = "lightblue", alpha = 0.5) +
tm_shape(rivers) +
  tm_lines(col = "blue") +
tm_layout(title = "Sacramento–San Joaquin Delta")
```
```{r}
sample_sites_sf <- st_as_sf(
  sample_sites,
  coords = c("Longitude", "Latitude"),  # order matters!
  crs = 4326
)
```

```{r}
ggplot() +
  geom_sf(data = st_crop(water_polygons, delta_bbox),
          fill = "lightblue", color = NA) +
  geom_sf(data = st_crop(rivers, delta_bbox),
          color = "blue", size = 0.3) +
  coord_sf(xlim = c(delta_bbox$xmin, delta_bbox$xmax),
           ylim = c(delta_bbox$ymin, delta_bbox$ymax)) +
  geom_sf(data = sample_sites_sf, color = "red", size = 2) +
  theme_minimal()
```

